### ISSUE TITLE
Not broadcasting?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/MuladdMacro.jl#8]
```julia
┌ Warning: `a::Number + b::AbstractArray` is deprecated, use `a .+b` instead.
│   caller = muladd at math.jl:1014 [inlined]
````

is showing up in some tests. That's caused by

```julia
julia> muladd(1, 1, ones(1))
┌ Warning: `a::Number + b::AbstractArray` is deprecated, use `a .+ b` instead.
│   caller = muladd(::Int64, ::Int64, ::Array{Float64,1}) at math.jl:1014
└ @ Base.Math ./math.jl:1014
```

@devmotion does the newest version not catch broadcasting as `muladd.(...)`? This is showing up in OrdinaryDiffEq.jl and StochasticDiffEq.jl tests.

**Comment by devmotion** [comment]
> @devmotion does the newest version not catch broadcasting as muladd.(...)? This is showing up in OrdinaryDiffEq.jl and StochasticDiffEq.jl tests.

It does, the new version passes all old tests plus some new tests (e.g. for subtractions). I noticed also some additional warnings like
```julia
┌ Warning: `a::Number - b::AbstractArray` is deprecated, use `a .- b` instead.
│   caller = ode_addsteps!(::Array{Array{Float64,1},1}, ::Float64, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::ODEFunction{false,typeof(test_ode),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}, ::Array{Float64,1}, ::OrdinaryDiffEq.Rosenbrock23ConstantCache{Float64,DiffEqDiffTools.TimeDerivativeWrapper{ODEFunction{false,typeof(test_ode),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1}},DiffEqDiffTools.UDerivativeWrapper{ODEFunction{false,typeof(test_ode),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,Array{Float64,1}}}, ::Bool, ::Bool, ::Bool) at stiff_addsteps.jl:7
└ @ OrdinaryDiffEq ~/build/JuliaDiffEq/OrdinaryDiffEq.jl/src/dense/stiff_addsteps.jl:7
```
Maybe these are similar issues, since any terms of the form
```julia
a * b + c
```
where `a` and `b` are scalars and `c` is an array will be converted to `muladd(a, b, c)` by `@muladd` and hence be problematic.

**Comment by devmotion** [comment]
Can you tell me which test caused the warning above? I had a look at the OrdinaryDiffEq tests and somehow couldn't find this warning but only a similar one caused by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/static_array_tests.jl#L12...

**Comment by devmotion** [comment]
OK, I can reproduce the warning with the following snippet which is taken from https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/test/first_rand_test.jl:
```julia
using StochasticDiffEq
f1(u,p,t) = 0.
g1(u,p,t) = 1.
dt = 1//2^(4)
prob1 = SDEProblem{false}(f1,g1,zeros(4),(0.0,1.0))
sol = solve(prob1,EM(),dt=dt,save_noise=true)
```
The warning is caused by the fact that https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/perform_step/low_order.jl#L4 is expanded to `K = (muladd)(dt, integrator.f(uprev, p, t), uprev)` (correctly, in my opinion) but both `dt` and the result of `integrator.f` are scalars whereas `uprev` is an array.

To me the issue seems to be that `f1` is not defined correctly since it returns a scalar although it should return an array, in my opinion. For this specific example a simple fix would be
```julia
f2(u,p,t) = zero(u)
prob2 = SDEProblem{false}(f2,g1,zeros(4),(0.0,1.0))
solve(prob2,EM(),dt=dt,save_noise=true)
```

**Comment by ChrisRackauckas** [comment]
Ahh, that would do it. Thanks! I was looking in the completely wrong place.

**Comment by ChrisRackauckas** [comment]
Looks like it, thanks.
